#!/bin/bash
echo "=== AQL Collections: Collect with Navigation ==="
echo "Navigate through relationships while collecting."
echo ""
echo "Ex 1: Get author names for all books"
echo "  AQL: library.books->collect(b | b.author.name)"
echo "  Result: ['George Orwell', 'George Orwell', 'Jane Austen', ...]"
echo ""
echo "Ex 2: Multi-property collect"
echo "  AQL: library.books->collect(b | Tuple{title=b.title, author=b.author.name})"
echo "  Result: [{title='1984', author='George Orwell'}, ...]"
echo ""
echo "Ex 3: Conditional collect"
echo "  AQL: library.books->collect(b | if b.available then b.title else 'N/A' endif)"
echo "  Result: ['1984', 'Animal Farm', 'N/A', 'Emma', ...]"
echo ""
echo "✅ Collect supports navigation and complex expressions"
