#!/bin/bash
echo "=== AQL Collections: Flatten Nested Collections ==="
echo "Handle complex nested structures."
echo ""
echo "Ex 1: Books by category (nested)"
echo "  library.categories->collect(c | c.books.title)"
echo "  Note: If categories reference books, get titles per category"
echo ""
echo "Ex 2: Multi-level flatten"
echo "  library.categories"
echo "    ->collect(c | c.books->collect(b | b.author.books))"
echo "    ->flatten()"
echo "    ->flatten()"
echo ""
echo "Ex 3: Flatten with unique filtering"
echo "  library.authors"
echo "    ->collect(a | a.books)"
echo "    ->flatten()"
echo "    ->asSet()"
echo "  Result: Unique books (removes duplicates)"
echo ""
echo "✅ Flatten handles arbitrary nesting depth"
