#!/bin/bash
echo "=== AQL Collections: Flatten Patterns ==="
echo "Common flatten usage patterns."
echo ""
echo "Pattern 1: Collect-Flatten-Collect"
echo "  collection->collect(transform)->flatten()->collect(extract)"
echo "  Use when: Transforming nested data then extracting properties"
echo ""
echo "Pattern 2: Flatten-Filter"
echo "  collection->flatten()->select(condition)"
echo "  Use when: Filtering across nested collections"
echo ""
echo "Pattern 3: Multiple Flatten"
echo "  collection->flatten()->flatten()"
echo "  Use when: Working with 3+ level nesting"
echo ""
echo "Ex: Get titles of all available books across authors"
echo "  library.authors"
echo "    ->collect(a | a.books->select(b | b.available))"
echo "    ->flatten()"
echo "    ->collect(b | b.title)"
echo ""
echo "✅ Flatten patterns simplify complex data access"
