#!/bin/bash
echo "=== AQL Collections: Nested Collect ==="
echo "Collect from collections of collections."
echo ""
echo "Ex 1: Get all books from all authors (nested)"
echo "  AQL: library.authors->collect(a | a.books)"
echo "  Result: [[Book1, Book2], [Book3], [Book4, Book5], ...]"
echo "  Note: Returns collection of collections"
echo ""
echo "Ex 2: Collect book titles per author"
echo "  AQL: library.authors->collect(a | a.books->collect(b | b.title))"
echo "  Result: [['1984', 'Animal Farm'], ['Pride and Prejudice'], ...]"
echo ""
echo "Ex 3: Author statistics"
echo "  AQL: library.authors->collect(a | Tuple{name=a.name, bookCount=a.books->size()})"
echo "  Result: [{name='George Orwell', bookCount=2}, ...]"
echo ""
echo "✅ Nested collect creates multi-dimensional data"
