#!/bin/bash
echo "=== AQL Collections: Advanced Patterns ==="
echo "Complex collection operation combinations."
echo ""
echo "Pattern 1: Pagination"
echo "  let pageSize = 10 in"
echo "  let pageNumber = 2 in"
echo "  library.books"
echo "    ->sortedBy(b | b.title)"
echo "    ->subSequence((pageNumber - 1) * pageSize, pageSize)"
echo ""
echo "Pattern 2: Grouping (manual)"
echo "  library.authors->collect(a | Tuple{"
echo "    nationality = a.nationality,"
echo "    authors = library.authors->select(a2 | a2.nationality = a.nationality)"
echo "  })->asSet()"
echo ""
echo "Pattern 3: Pivot table"
echo "  library.categories->collect(c | Tuple{"
echo "    category = c.name,"
echo "    bookCount = c.books->size(),"
echo "    totalPages = c.books->collect(b | b.pages)->sum(),"
echo "    avgRating = c.books->collect(b | b.rating)->sum() / c.books->size()"
echo "  })"
echo ""
echo "Pattern 4: Ranking"
echo "  library.books"
echo "    ->sortedBy(b | b.rating)->reverse()"
echo "    ->collect(b | Tuple{rank=library.books->indexOf(b)+1, title=b.title})"
echo ""
echo "Pattern 5: Cross-tabulation"
echo "  library.authors->collect(a1 | library.authors->collect(a2 | Tuple{"
echo "    author1 = a1.name,"
echo "    author2 = a2.name,"
echo "    sharedPages = a1.books->intersection(a2.books)->collect(b | b.pages)->sum()"
echo "  }))->flatten()"
echo ""
echo "✅ Advanced patterns enable sophisticated data analysis"
