#!/bin/bash
echo "=== AQL Collections: Aggregate Patterns ==="
echo "Combine multiple aggregations."
echo ""
echo "Pattern 1: Statistical Summary"
echo "  let pages = library.books->collect(b | b.pages) in"
echo "  Tuple{"
echo "    total = pages->sum(),"
echo "    average = pages->sum() / pages->size(),"
echo "    min = pages->min(),"
echo "    max = pages->max(),"
echo "    count = pages->size()"
echo "  }"
echo ""
echo "Pattern 2: Group Aggregation"
echo "  library.authors->collect(a | Tuple{"
echo "    author = a.name,"
echo "    totalPages = a.books->collect(b | b.pages)->sum(),"
echo "    avgRating = a.books->collect(b | b.rating)->sum() / a.books->size()"
echo "  })"
echo ""
echo "Pattern 3: Conditional Aggregation"
echo "  Tuple{"
echo "    available = library.books->select(b | b.available)->size(),"
echo "    unavailable = library.books->reject(b | b.available)->size()"
echo "  }"
echo ""
echo "✅ Aggregate patterns provide comprehensive statistics"
