#!/bin/bash
echo "=== AQL Collections: Flatten Operation ==="
echo "Flatten converts collection of collections into single collection."
echo ""
echo "Ex 1: Flatten nested book collections"
echo "  AQL: library.authors->collect(a | a.books)->flatten()"
echo "  Before flatten: [[Book1, Book2], [Book3], [Book4, Book5]]"
echo "  After flatten: [Book1, Book2, Book3, Book4, Book5]"
echo ""
echo "Ex 2: Get all book titles (flattened)"
echo "  AQL: library.authors->collect(a | a.books)->flatten()->collect(b | b.title)"
echo "  Result: ['1984', 'Animal Farm', 'Pride and Prejudice', ...]"
echo ""
echo "Ex 3: Unique author nationalities"
echo "  AQL: library.authors.nationality->asSet()"
echo "  Result: {'British', 'American', 'Russian', 'Colombian'}"
echo ""
echo "✅ Flatten simplifies nested collections"
