#!/bin/bash
echo "=== AQL Collections: Max and Min ==="
echo "Find maximum and minimum values."
echo ""
echo "Ex 1: Longest book"
echo "  AQL: library.books->collect(b | b.pages)->max()"
echo "  Result: 1296 (War and Peace)"
echo ""
echo "Ex 2: Shortest book"
echo "  AQL: library.books->collect(b | b.pages)->min()"
echo "  Result: 127 (The Old Man and the Sea)"
echo ""
echo "Ex 3: Highest rating"
echo "  AQL: library.books->collect(b | b.rating)->max()"
echo "  Result: 4.9"
echo ""
echo "Ex 4: Find book with max pages"
echo "  let maxPages = library.books->collect(b | b.pages)->max() in"
echo "  library.books->select(b | b.pages = maxPages)"
echo ""
echo "Ex 5: Rating range"
echo "  let minRating = library.books->collect(b | b.rating)->min() in"
echo "  let maxRating = library.books->collect(b | b.rating)->max() in"
echo "  maxRating - minRating"
echo ""
echo "✅ Max/Min find extremes in numeric collections"
