#!/bin/bash
echo "=== AQL Collections: First and Last ==="
echo "Extract elements from collection ends."
echo ""
echo "Ex 1: First N elements"
echo "  AQL: library.books->first(5)"
echo "  Result: First 5 books"
echo ""
echo "Ex 2: Last N elements"
echo "  AQL: library.books->last(3)"
echo "  Result: Last 3 books"
echo ""
echo "Ex 3: Top-rated books"
echo "  AQL: library.books->sortedBy(b | b.rating)->reverse()->first(5)"
echo "  Result: 5 highest-rated books"
echo ""
echo "Ex 4: Single element access"
echo "  AQL: library.books->sortedBy(b | b.pages)->last(1)"
echo "  Result: Longest book (as collection)"
echo ""
echo "Ex 5: Filtered then limited"
echo "  library.books"
echo "    ->select(b | b.available)"
echo "    ->sortedBy(b | b.rating)->reverse()"
echo "    ->first(3)"
echo "  Result: Top 3 available books by rating"
echo ""
echo "✅ First/Last enable top-N queries"
