#!/bin/bash
echo "=== AQL Collections: Counting Operations ==="
echo "Count elements with size() and aggregate counting."
echo ""
echo "Ex 1: Total books"
echo "  AQL: library.books->size()"
echo "  Result: 29"
echo ""
echo "Ex 2: Available books count"
echo "  AQL: library.books->select(b | b.available)->size()"
echo "  Result: Count of available books"
echo ""
echo "Ex 3: Books per author"
echo "  AQL: library.authors->collect(a | Tuple{name=a.name, count=a.books->size()})"
echo "  Result: [{name='George Orwell', count=2}, ...]"
echo ""
echo "Ex 4: Count by condition"
echo "  let longBooks = library.books->select(b | b.pages > 400)->size() in"
echo "  let shortBooks = library.books->select(b | b.pages <= 400)->size() in"
echo "  Tuple{long=longBooks, short=shortBooks}"
echo ""
echo "Ex 5: Percentage available"
echo "  (library.books->select(b | b.available)->size() * 100.0) /"
echo "  library.books->size()"
echo ""
echo "✅ Size() enables counting and percentages"
