#!/bin/bash
echo "=== AQL Collections: Collect Operation ==="
echo "Collect transforms each element in a collection."
echo ""
echo "Ex 1: Get all book titles"
echo "  AQL: library.books->collect(b | b.title)"
echo "  Result: ['1984', 'Animal Farm', 'Pride and Prejudice', ...]"
echo ""
echo "Ex 2: Get all page counts"
echo "  AQL: library.books->collect(b | b.pages)"
echo "  Result: [328, 141, 432, 474, ...]"
echo ""
echo "Ex 3: Transform to readable format"
echo "  AQL: library.books->collect(b | b.title + ' (' + b.pages.toString() + ' pages)')"
echo "  Result: ['1984 (328 pages)', 'Animal Farm (141 pages)', ...]"
echo ""
echo "✅ Collect extracts/transforms properties from collections"
