#!/bin/bash
echo "=== AQL Collections: Union and Intersection ==="
echo "Combine or intersect collections."
echo ""
echo "Ex 1: Union - combine two sets"
echo "  let britishAuthors = library.authors->select(a | a.nationality = 'British') in"
echo "  let americanAuthors = library.authors->select(a | a.nationality = 'American') in"
echo "  britishAuthors->union(americanAuthors)"
echo "  Result: All British and American authors"
echo ""
echo "Ex 2: Intersection - find common elements"
echo "  let highRated = library.books->select(b | b.rating >= 4.5) in"
echo "  let available = library.books->select(b | b.available) in"
echo "  highRated->intersection(available)"
echo "  Result: High-rated AND available books"
echo ""
echo "Ex 3: Difference - elements in A but not B"
echo "  let allBooks = library.books in"
echo "  let availableBooks = library.books->select(b | b.available) in"
echo "  allBooks->select(b | not availableBooks->includes(b))"
echo "  Result: Unavailable books"
echo ""
echo "✅ Set operations enable complex filtering logic"
