#!/bin/bash
echo "=== AQL Collections: SortedBy Operation ==="
echo "Sort collections by property or expression."
echo ""
echo "Ex 1: Sort books by title"
echo "  AQL: library.books->sortedBy(b | b.title)"
echo "  Result: Books in alphabetical order"
echo ""
echo "Ex 2: Sort by pages (ascending)"
echo "  AQL: library.books->sortedBy(b | b.pages)"
echo "  Result: Shortest to longest"
echo ""
echo "Ex 3: Sort by rating (descending)"
echo "  AQL: library.books->sortedBy(b | b.rating)->reverse()"
echo "  Result: Highest rated first"
echo ""
echo "Ex 4: Multi-criteria sort"
echo "  library.books->sortedBy(b | b.rating)->reverse()->first(5)"
echo "  Result: Top 5 rated books"
echo ""
echo "Ex 5: Sort by complex expression"
echo "  library.books->sortedBy(b | b.pages * b.rating)"
echo "  Result: Sort by 'value' (pages × rating)"
echo ""
echo "✅ SortedBy orders collections by any criterion"
