#!/bin/bash
echo "=== AQL Collections: Collect for Transformation ==="
echo "Transform data structure with collect."
echo ""
echo "Ex 1: Calculate reading time estimates"
echo "  AQL: library.books->collect(b | Tuple{title=b.title, hours=(b.pages/50).round()})"
echo "  Logic: ~50 pages per hour reading speed"
echo "  Result: [{title='1984', hours=7}, {title='Animal Farm', hours=3}, ...]"
echo ""
echo "Ex 2: Price estimation (hypothetical)"
echo "  AQL: library.books->collect(b | b.pages * 0.03)"
echo "  Result: Estimated prices based on page count"
echo ""
echo "Ex 3: Categorization"
echo "  AQL: library.books->collect(b | if b.pages > 400 then 'Long' else if b.pages > 200 then 'Medium' else 'Short' endif endif)"
echo "  Result: ['Short', 'Short', 'Long', 'Long', ...]"
echo ""
echo "✅ Collect enables data transformation and enrichment"
