#!/bin/bash
echo "=== AQL Collections: Chained Flatten ==="
echo "Multiple flatten operations for deeply nested structures."
echo ""
echo "Ex 1: Three-level nesting (hypothetical)"
echo "  library.categories"
echo "    ->collect(c | c.books)"
echo "    ->flatten()"
echo "    ->collect(b | b.author.books)"
echo "    ->flatten()"
echo ""
echo "Ex 2: Flatten with filtering"
echo "  library.authors"
echo "    ->collect(a | a.books->select(b | b.available))"
echo "    ->flatten()"
echo ""
echo "Ex 3: Flatten then aggregate"
echo "  library.authors"
echo "    ->collect(a | a.books)"
echo "    ->flatten()"
echo "    ->collect(b | b.pages)"
echo "    ->sum()"
echo "  Result: Total pages across all books"
echo ""
echo "✅ Chain flatten with other operations for complex queries"
