#!/bin/bash
echo "=== AQL Collections: Sum Aggregation ==="
echo "Sum calculates total of numeric values."
echo ""
echo "Ex 1: Total pages in library"
echo "  AQL: library.books->collect(b | b.pages)->sum()"
echo "  Result: Sum of all page counts"
echo "  Example: 328+141+432+... = ~8000+ pages"
echo ""
echo "Ex 2: Average pages per book"
echo "  AQL: library.books->collect(b | b.pages)->sum() / library.books->size()"
echo "  Result: Mean page count"
echo ""
echo "Ex 3: Total pages for available books"
echo "  AQL: library.books->select(b | b.available)->collect(b | b.pages)->sum()"
echo ""
echo "Ex 4: Pages by author"
echo "  AQL: library.authors->collect(a | a.books->collect(b | b.pages)->sum())"
echo "  Result: Total pages written per author"
echo ""
echo "✅ Sum aggregates numeric collections"
