<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="organisation"
    nsURI="http://swift-modelling.org/test/organisation"
    nsPrefix="org">
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Person">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="age"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Team">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="members"
        upperBound="-1"
        eType="#//Person"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="leader"
        lowerBound="1"
        eType="#//Person"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Organisation">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="teams"
        upperBound="-1"
        eType="#//Team"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
