#!/bin/bash
# AQL-01 Step 12: Combined Expressions

echo "=== AQL Basics: Combined Expressions ==="
echo ""
echo "Complex AQL expressions combine multiple operations, navigation,"
echo "and function calls to create powerful queries."
echo ""
echo "Example 1: Age classification with conditional logic"
echo "  AQL:"
echo "    if employee.age >= 50 then"
echo "      'Senior'"
echo "    else if employee.age >= 30 then"
echo "      'Mid-level'"
echo "    else"
echo "      'Junior'"
echo "    endif endif"
echo ""
echo "  For Alice (age 32): Result = 'Mid-level'"
echo "  For Bob (age 45): Result = 'Mid-level'"
echo "  For Frank (age 51): Result = 'Senior'"
echo ""
echo "Example 2: Employee description with multiple properties"
echo "  AQL:"
echo "    employee.name + ' (' + employee.age.toString() + ' years old, ' +"
echo "    employee.department + ' department)'"
echo ""
echo "  Result for Alice: 'Alice Johnson (32 years old, Engineering department)'"
echo ""
echo "Example 3: Department statistics"
echo "  AQL:"
echo "    employee.department + ': ' +"
echo "    company.employees->select(e | e.department = employee.department)->size().toString() +"
echo "    ' employees'"
echo ""
echo "  For an Engineering employee: 'Engineering: 3 employees'"
echo "  (Alice, Carol, and Frank are all in Engineering)"
echo ""
echo "Example 4: Complex filtering and navigation"
echo "  AQL:"
echo "    company.employees"
echo "      ->select(e | e.age > 30)"
echo "      ->collect(e | e.name + ' (' + e.department + ')')"
echo "      ->sortedBy(name | name)"
echo ""
echo "  Result: Sorted list of employees over 30 with their departments"
echo "  ['Bob Smith (Sales)', 'David Brown (Marketing)', 'Frank Miller (Engineering)', ...]"
echo ""
echo "Example 5: Aggregation with conditions"
echo "  AQL:"
echo "    'Average age of Engineering employees: ' +"
echo "    (company.employees"
echo "      ->select(e | e.department = 'Engineering')"
echo "      ->collect(e | e.age)"
echo "      ->sum() / company.employees"
echo "      ->select(e | e.department = 'Engineering')"
echo "      ->size()).toString()"
echo ""
echo "  Calculates: (32 + 28 + 51) / 3 = 37"
echo "  Result: 'Average age of Engineering employees: 37'"
echo ""
echo "Key Techniques Demonstrated:"
echo "  ✓ Nested conditionals (if-then-else-endif)"
echo "  ✓ String concatenation with type conversion"
echo "  ✓ Collection operations (select, collect, size, sum)"
echo "  ✓ Method chaining (->select()->collect()->sortedBy())"
echo "  ✓ Arithmetic within expressions"
echo "  ✓ Multi-line expression formatting for readability"
echo ""
echo "These patterns form the foundation for complex model queries"
echo "used in ATL transformations and MTL templates."
