#!/bin/bash
# AQL-01 Step 8: Safe Navigation

echo "=== AQL Basics: Safe Navigation ==="
echo ""
echo "Handle optional references safely to avoid null reference errors:"
echo ""
echo "Method 1: Conditional check before accessing"
echo "  AQL Expression:"
echo "  if employee.manager <> null then"
echo "    employee.manager.name"
echo "  else"
echo "    'No manager'"
echo "  endif"
echo ""
echo "Method 2: Using oclIsUndefined() check"
echo "  AQL Expression:"
echo "  if not employee.manager.oclIsUndefined() then"
echo "    employee.manager.name"
echo "  else"
echo "    'Direct report to CEO'"
echo "  endif"
echo ""
echo "Method 3: Default value pattern"
echo "  AQL Expression:"
echo "  employee.manager.name"
echo "  With proper null handling in the context"
echo ""
echo "Example with our Company model:"
echo "  Since employees might not have all optional fields,"
echo "  check before accessing:"
echo ""
echo "  if employee.middleName <> null then"
echo "    employee.firstName + ' ' + employee.middleName + ' ' + employee.lastName"
echo "  else"
echo "    employee.firstName + ' ' + employee.lastName"
echo "  endif"
echo ""
echo "Key Points:"
echo "  - Always check optional references before accessing their properties"
echo "  - Use 'if-then-else-endif' for safe navigation"
echo "  - Provide sensible default values when references are null"
