#!/bin/bash
# AQL-01 Step 4: Literal Values

echo "=== AQL Basics: Literal Values ==="
echo ""
echo "String literals (enclosed in single quotes):"
echo "  'Hello World'     - String literal"
echo "  'TechCorp'        - Another string"
echo "  'Engineering'     - Department name"
echo ""
echo "Numeric literals:"
echo "  42                - Integer literal"
echo "  3.14              - Real number literal"
echo "  -5                - Negative integer"
echo "  0.5               - Fractional number"
echo ""
echo "Boolean literals:"
echo "  true              - Boolean true"
echo "  false             - Boolean false"
echo ""
echo "Using literals in expressions:"
echo "  employee.age + 1              - Add integer literal"
echo "  employee.name + ' Smith'      - Concatenate string literal"
echo "  employee.age > 30             - Compare with integer literal"
echo "  employee.department = 'Sales' - Compare with string literal"
