#!/bin/bash
# AQL-01 Step 7: Combined Navigation

echo "=== AQL Basics: Combined Navigation ==="
echo ""
echo "Chain multiple navigation steps together to access deeply nested properties:"
echo ""
echo "Example 1: Multi-step property access"
echo "  AQL Expression: company.employees.department"
echo "  Step 1: company → Get the company object"
echo "  Step 2: .employees → Navigate to all employees (collection)"
echo "  Step 3: .department → Get department from each employee (collection of strings)"
echo ""
echo "Example 2: If we had Projects with Teams with Members"
echo "  AQL Expression: company.projects.teams.members.name"
echo "  Navigates: company → projects → teams → members → name"
echo "  Returns: All member names across all teams in all projects"
echo ""
echo "Example 3: Combining with other operations"
echo "  AQL Expression: company.employees.age"
echo "  Then use with operations: company.employees.age->sum()"
echo "  Returns: Total sum of all employee ages"
echo ""
echo "Key Points:"
echo "  - Navigation is left-to-right"
echo "  - Each step operates on the result of the previous step"
echo "  - Collections propagate through navigation chains"
echo "  - Can combine navigation with operators (shown in later steps)"
