#!/bin/bash
# AQL-01 Step 6: Multi-valued Navigation

echo "=== AQL Basics: Multi-valued Navigation ==="
echo ""
echo "Navigate through collections (multi-valued references):"
echo ""
echo "Example 1: Get all employees"
echo "  AQL Expression: company.employees"
echo "  Returns: Collection of all Employee objects"
echo "  Result: [Alice Johnson, Bob Smith, Carol Williams, ...]"
echo ""
echo "Example 2: Get all employee names"
echo "  AQL Expression: company.employees.name"
echo "  Returns: Collection of all employee names (Strings)"
echo "  Result: ['Alice Johnson', 'Bob Smith', 'Carol Williams', ...]"
echo ""
echo "Example 3: Get all employee ages"
echo "  AQL Expression: company.employees.age"
echo "  Returns: Collection of integers"
echo "  Result: [32, 45, 28, 38, 29, 51]"
echo ""
echo "Example 4: Get all departments"
echo "  AQL Expression: company.employees.department"
echo "  Returns: Collection of department names (may include duplicates)"
echo "  Result: ['Engineering', 'Sales', 'Engineering', 'Marketing', 'HR', 'Engineering']"
echo ""
echo "Key Point: When navigating from a collection, the result is also a collection"
