#!/bin/bash
# AQL-01 Step 10: String Operations

echo "=== AQL Basics: String Operations ==="
echo ""
echo "String concatenation (+):"
echo "  AQL: employee.name + ' (' + employee.department + ')'"
echo "  Example: 'Alice Johnson' + ' (' + 'Engineering' + ')'"
echo "  Result: 'Alice Johnson (Engineering)'"
echo ""
echo "  AQL: 'Employee: ' + employee.name"
echo "  Example: 'Employee: ' + 'Bob Smith'"
echo "  Result: 'Employee: Bob Smith'"
echo ""
echo "String length (size()):"
echo "  AQL: employee.name.size()"
echo "  Example: 'Alice Johnson'.size()"
echo "  Result: 13"
echo ""
echo "  AQL: employee.department.size()"
echo "  Example: 'Engineering'.size()"
echo "  Result: 11"
echo ""
echo "Case conversion:"
echo "  AQL: employee.name.toUpperCase()"
echo "  Example: 'Alice Johnson'.toUpperCase()"
echo "  Result: 'ALICE JOHNSON'"
echo ""
echo "  AQL: employee.name.toLowerCase()"
echo "  Example: 'Bob Smith'.toLowerCase()"
echo "  Result: 'bob smith'"
echo ""
echo "Substring operations:"
echo "  AQL: employee.name.substring(1, 5)"
echo "  Example: 'Alice Johnson'.substring(1, 5)"
echo "  Result: 'Alice' (first 5 characters starting at position 1)"
echo ""
echo "Combined string operations:"
echo "  AQL: employee.name.toUpperCase() + ' - ' + employee.department.toLowerCase()"
echo "  Example: 'ALICE JOHNSON - engineering'"
echo ""
echo "Checking string content:"
echo "  AQL: employee.department.startsWith('Eng')"
echo "  Result: true (for 'Engineering')"
echo ""
echo "  AQL: employee.name.contains('John')"
echo "  Result: true (for 'Alice Johnson')"
