#!/bin/bash
echo "=== AQL Complex Patterns: Recursive Navigation ==="
echo ""
echo "Handle hierarchical and recursive model structures."
echo ""
echo "Ex 1: eAllContents - recursive containment traversal"
echo "  library.eAllContents()"
echo "  Result: All objects recursively contained (books, authors, categories, etc.)"
echo ""
echo "  library.eAllContents()->select(e | e.oclIsKindOf(Book))->size()"
echo "  Result: Count of all books at any depth"
echo ""
echo "Ex 2: eContainer - navigate up containment hierarchy"
echo "  library.books->first().eContainer()"
echo "  Result: The library containing the book"
echo ""
echo "  library.books->first().eContainer().eContainer()"
echo "  Result: Container of the library (null if root)"
echo ""
echo "Ex 3: Recursive function simulation with closure"
echo "  -- Find all categories and subcategories (if hierarchical)"
echo "  -- Assume Category has 'subcategories' reference"
echo "  rootCategory->closure(c | c.subcategories)"
echo "  Result: Root category and all nested subcategories"
echo ""
echo "Ex 4: Path to root"
echo "  -- Build path from element to root container"
echo "  let book = library.books->first() in"
echo "  Sequence{book, book.eContainer(), book.eContainer().eContainer()}"
echo "    ->select(e | e <> null)"
echo "  Result: [Book, Library, null] -> [Book, Library]"
echo ""
echo "Ex 5: Depth calculation"
echo "  -- Calculate containment depth (manual iteration)"
echo "  let element = library.books->first() in"
echo "  let depth = if element.eContainer() = null then 0"
echo "              else if element.eContainer().eContainer() = null then 1"
echo "              else if element.eContainer().eContainer().eContainer() = null then 2"
echo "              else 3"
echo "              endif endif endif in"
echo "  Tuple{element = element, depth = depth}"
echo "  Result: {element: Book, depth: 1} (assuming Library is root)"
echo ""
echo "Ex 6: Find common ancestor"
echo "  -- Find lowest common ancestor of two elements"
echo "  let book1 = library.books->first() in"
echo "  let book2 = library.books->last() in"
echo "  -- Both have library as direct container, so:"
echo "  book1.eContainer()  -- Returns library"
echo "  Result: Library (common ancestor)"
echo ""
echo "Ex 7: Recursive type filtering"
echo "  library.eAllContents()"
echo "    ->select(e | e.eClass().name.startsWith('Book'))"
echo "  Result: All objects whose type starts with 'Book' at any depth"
echo ""
echo "✅ eAllContents() traverses full containment tree"
echo "✅ eContainer() navigates up the hierarchy"
echo "✅ closure() computes transitive relationships"
