#!/bin/bash
echo "=== Workflow 02: Model Validation Constraints ==="
echo ""
echo "Define and check business rules on project models using AQL."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "CONSTRAINT 1: All tasks must have an assignee"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  AQL Query:"
echo "  project.tasks->select(t | t.assignedTo = null)"
echo ""
echo "  Expected violations:"
echo "    - Task 'Documentation' (no assignee)"
echo ""
echo "  Severity: ERROR"
echo "  Message: 'Task must be assigned to a team member'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "CONSTRAINT 2: Estimated hours must be positive"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  AQL Query:"
echo "  project.tasks->select(t | t.estimatedHours <= 0)"
echo ""
echo "  Expected violations: None (all tasks have positive estimates)"
echo ""
echo "  Severity: ERROR"
echo "  Message: 'Estimated hours must be greater than zero'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "CONSTRAINT 3: Actual hours should not exceed estimate by >50%"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  AQL Query:"
echo "  project.tasks"
echo "    ->select(t | t.actualHours > 0)"
echo "    ->select(t | t.actualHours > t.estimatedHours * 1.5)"
echo ""
echo "  Expected violations: None (closest is UI/UX: 90/80 = 112.5%)"
echo ""
echo "  Severity: WARNING"
echo "  Message: 'Task significantly over budget'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "CONSTRAINT 4: Circular dependencies are not allowed"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  AQL Query:"
echo "  project.tasks->select(t |"
echo "    t->closure(task | task.dependencies)->includes(t)"
echo "  )"
echo ""
echo "  Expected violations: None in current instance"
echo "  (closure() would detect cycles if present)"
echo ""
echo "  Severity: ERROR"
echo "  Message: 'Circular dependency detected'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "CONSTRAINT 5: Team member workload capacity"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  AQL Query:"
echo "  let assignedHours = project.members->collect(m | Tuple{"
echo "    member = m,"
echo "    totalHours = project.tasks"
echo "      ->select(t | t.assignedTo = m and t.status <> TaskStatus::COMPLETED)"
echo "      ->collect(t | t.estimatedHours - t.actualHours)"
echo "      ->sum()"
echo "  }) in"
echo "  assignedHours->select(t | t.totalHours > t.member.maxHoursPerWeek * 12)"
echo ""
echo "  Expected violations:"
echo "    - Bob Martinez: (120-95) + (100-85) + 50 = 90 hours remaining"
echo "      Over 3-month capacity: 35 * 12 = 420 hours (OK)"
echo ""
echo "  Severity: WARNING"
echo "  Message: 'Team member over-allocated'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "CONSTRAINT 6: Critical tasks must not be blocked"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  AQL Query:"
echo "  project.tasks->select(t |"
echo "    t.priority = Priority::CRITICAL and"
echo "    t.status = TaskStatus::BLOCKED"
echo "  )"
echo ""
echo "  Expected violations:"
echo "    - Task 'Deployment' (CRITICAL + BLOCKED)"
echo ""
echo "  Severity: ERROR"
echo "  Message: 'Critical task is blocked - requires immediate attention'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "CONSTRAINT 7: Dependencies must be completed before task can start"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  AQL Query:"
echo "  project.tasks->select(t |"
echo "    t.status = TaskStatus::IN_PROGRESS and"
echo "    t.dependencies->exists(d | d.status <> TaskStatus::COMPLETED)"
echo "  )"
echo ""
echo "  Expected violations: None (in-progress tasks have completed dependencies)"
echo ""
echo "  Severity: ERROR"
echo "  Message: 'Cannot start task with incomplete dependencies'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "SUMMARY: Validation Results"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Errors: 2"
echo "    - Task 'Documentation' has no assignee"
echo "    - Task 'Deployment' is critical but blocked"
echo ""
echo "  Warnings: 0"
echo ""
echo "✅ Validation constraints enforced via AQL queries"
echo "✅ Business rules checked automatically"
echo "✅ Model quality ensured before further processing"
