#!/bin/bash
echo "=== Workflow 02: Generate Validation Report ==="
echo ""
echo "Use AQL to generate a comprehensive validation report."
echo ""
echo "swift-aql query workflow-02-step-02-project-instance.xmi \\"
echo "  --output validation-report.json \\"
echo "  --query '\\"
echo "let project = Project.allInstances()->first() in"
echo "Tuple{"
echo "  projectName = project.name,"
echo "  validationDate = \"2024-01-15T14:30:00Z\","
echo "  summary = Tuple{"
echo "    totalTasks = project.tasks->size(),"
echo "    completedTasks = project.tasks->select(t | t.status = TaskStatus::COMPLETED)->size(),"
echo "    inProgressTasks = project.tasks->select(t | t.status = TaskStatus::IN_PROGRESS)->size(),"
echo "    blockedTasks = project.tasks->select(t | t.status = TaskStatus::BLOCKED)->size(),"
echo "    errorCount = 2,"
echo "    warningCount = 0"
echo "  },"
echo "  errors = Sequence{"
echo "    Tuple{"
echo "      severity = \"ERROR\","
echo "      constraint = \"C001-TaskAssignment\","
echo "      message = \"Task must be assigned to a team member\","
echo "      element = \"Task[Documentation]\","
echo "      location = \"project.tasks[7]\""
echo "    },"
echo "    Tuple{"
echo "      severity = \"ERROR\","
echo "      constraint = \"C006-CriticalBlocked\","
echo "      message = \"Critical task is blocked\","
echo "      element = \"Task[Deployment]\","
echo "      location = \"project.tasks[8]\""
echo "    }"
echo "  },"
echo "  warnings = Sequence{},"
echo "  metrics = Tuple{"
echo "    totalEstimatedHours = project.tasks->collect(t | t.estimatedHours)->sum(),"
echo "    totalActualHours = project.tasks->collect(t | t.actualHours)->sum(),"
echo "    remainingHours = project.tasks"
echo "      ->select(t | t.status <> TaskStatus::COMPLETED)"
echo "      ->collect(t | t.estimatedHours - t.actualHours)"
echo "      ->sum(),"
echo "    completionPercentage = (project.tasks"
echo "      ->select(t | t.status = TaskStatus::COMPLETED)->size() * 100.0)"
echo "      / project.tasks->size(),"
echo "    budgetUtilization = (project.tasks->collect(t | t.actualHours)->sum() * 100.0)"
echo "      / project.budget"
echo "  },"
echo "  teamWorkload = project.members->collect(m | Tuple{"
echo "    memberName = m.name,"
echo "    role = m.role,"
echo "    assignedTasks = project.tasks->select(t | t.assignedTo = m)->size(),"
echo "    totalHours = project.tasks"
echo "      ->select(t | t.assignedTo = m)"
echo "      ->collect(t | t.estimatedHours)"
echo "      ->sum(),"
echo "    completedHours = project.tasks"
echo "      ->select(t | t.assignedTo = m and t.status = TaskStatus::COMPLETED)"
echo "      ->collect(t | t.actualHours)"
echo "      ->sum()"
echo "  })"
echo "}'"
echo ""
echo "Expected Output (validation-report.json):"
echo "{"
echo "  \"projectName\": \"Website Redesign\","
echo "  \"validationDate\": \"2024-01-15T14:30:00Z\","
echo "  \"summary\": {"
echo "    \"totalTasks\": 10,"
echo "    \"completedTasks\": 2,"
echo "    \"inProgressTasks\": 2,"
echo "    \"blockedTasks\": 1,"
echo "    \"errorCount\": 2,"
echo "    \"warningCount\": 0"
echo "  },"
echo "  \"errors\": ["
echo "    {"
echo "      \"severity\": \"ERROR\","
echo "      \"constraint\": \"C001-TaskAssignment\","
echo "      \"message\": \"Task must be assigned to a team member\","
echo "      \"element\": \"Task[Documentation]\","
echo "      \"location\": \"project.tasks[7]\""
echo "    },"
echo "    {"
echo "      \"severity\": \"ERROR\","
echo "      \"constraint\": \"C006-CriticalBlocked\","
echo "      \"message\": \"Critical task is blocked\","
echo "      \"element\": \"Task[Deployment]\","
echo "      \"location\": \"project.tasks[8]\""
echo "    }"
echo "  ],"
echo "  \"warnings\": [],"
echo "  \"metrics\": {"
echo "    \"totalEstimatedHours\": 580,"
echo "    \"totalActualHours\": 315,"
echo "    \"remainingHours\": 265,"
echo "    \"completionPercentage\": 20.0,"
echo "    \"budgetUtilization\": 0.63"
echo "  },"
echo "  \"teamWorkload\": ["
echo "    {"
echo "      \"memberName\": \"Alice Chen\","
echo "      \"role\": \"Project Manager\","
echo "      \"assignedTasks\": 3,"
echo "      \"totalHours\": 100,"
echo "      \"completedHours\": 45"
echo "    },"
echo "    {"
echo "      \"memberName\": \"Bob Martinez\","
echo "      \"role\": \"Senior Developer\","
echo "      \"assignedTasks\": 3,"
echo "      \"totalHours\": 270,"
echo "      \"completedHours\": 180"
echo "    },"
echo "    {"
echo "      \"memberName\": \"Carol Williams\","
echo "      \"role\": \"Junior Developer\","
echo "      \"assignedTasks\": 2,"
echo "      \"totalHours\": 100,"
echo "      \"completedHours\": 0"
echo "    },"
echo "    {"
echo "      \"memberName\": \"David Kim\","
echo "      \"role\": \"Designer\","
echo "      \"assignedTasks\": 1,"
echo "      \"totalHours\": 80,"
echo "      \"completedHours\": 90"
echo "    }"
echo "  ]"
echo "}"
echo ""
echo "✅ Comprehensive validation report generated from model"
echo "✅ Includes errors, warnings, metrics, and team workload"
echo "✅ Ready for stakeholder review and decision-making"
