#!/bin/bash
echo "=== AQL Advanced: Tuple Construction ==="
echo ""
echo "Tuples combine multiple values into structured records."
echo ""
echo "Ex 1: Simple tuple"
echo "  Tuple{title='Book Title', pages=350}"
echo "  Result: {title: 'Book Title', pages: 350}"
echo ""
echo "Ex 2: Tuple from model element"
echo "  library.books->collect(b | Tuple{"
echo "    title = b.title,"
echo "    author = b.authors->first().name,"
echo "    rating = b.rating"
echo "  })"
echo "  Result: [{title: '1984', author: 'Orwell', rating: 4.8}, ...]"
echo ""
echo "Ex 3: Nested tuples"
echo "  library.authors->collect(a | Tuple{"
echo "    author = a.name,"
echo "    stats = Tuple{"
echo "      bookCount = a.books->size(),"
echo "      avgPages = a.books->collect(b | b.pages)->sum() / a.books->size(),"
echo "      totalRating = a.books->collect(b | b.rating)->sum()"
echo "    }"
echo "  })"
echo "  Result: Nested structure with author statistics"
echo ""
echo "Ex 4: Tuple with computed fields"
echo "  library.books->collect(b | Tuple{"
echo "    title = b.title,"
echo "    pages = b.pages,"
echo "    readingTime = (b.pages / 250.0) * 60,  -- minutes at 250 wpm"
echo "    quality = if b.rating >= 4.5 then 'Excellent'"
echo "              else if b.rating >= 4.0 then 'Good'"
echo "              else 'Average'"
echo "              endif endif"
echo "  })"
echo "  Result: Books with derived reading time and quality rating"
echo ""
echo "Ex 5: Aggregation tuple"
echo "  let allBooks = library.books in"
echo "  Tuple{"
echo "    totalBooks = allBooks->size(),"
echo "    totalPages = allBooks->collect(b | b.pages)->sum(),"
echo "    avgRating = allBooks->collect(b | b.rating)->sum() / allBooks->size(),"
echo "    categories = library.categories->collect(c | c.name)->asSet()"
echo "  }"
echo "  Result: Library summary statistics"
echo ""
echo "✅ Tuples create ad-hoc data structures without metamodel changes"
echo "✅ Essential for reporting and data transformation"
echo "✅ Support nested and computed fields"
