#!/bin/bash
echo "=== AQL Advanced: Complex Navigation ==="
echo ""
echo "Navigate through multiple levels of relationships efficiently."
echo ""
echo "Ex 1: Multi-hop navigation"
echo "  library.categories->collect(c | c.books)->flatten()"
echo "    ->collect(b | b.authors)->flatten()"
echo "    ->asSet()"
echo "  Result: All authors who wrote books in any category"
echo ""
echo "Ex 2: Reverse navigation"
echo "  -- Find categories for a specific book"
echo "  let targetBook = library.books->select(b | b.title = '1984')->first() in"
echo "  library.categories->select(c | c.books->includes(targetBook))"
echo "  Result: Categories containing '1984'"
echo ""
echo "Ex 3: Cross-reference navigation"
echo "  -- Authors who co-authored with a specific author"
echo "  let author = library.authors->select(a | a.name = 'Orwell')->first() in"
echo "  author.books->collect(b | b.authors)->flatten()"
echo "    ->select(a | a <> author)"
echo "    ->asSet()"
echo "  Result: Orwell's co-authors"
echo ""
echo "Ex 4: Conditional navigation"
echo "  library.authors->collect(a |"
echo "    if a.books->size() > 5 then"
echo "      a.books->select(b | b.rating >= 4.5)"
echo "    else"
echo "      a.books"
echo "    endif"
echo "  )->flatten()"
echo "  Result: For prolific authors, only top-rated books; all books for others"
echo ""
echo "Ex 5: Deep traversal with filtering"
echo "  library.categories"
echo "    ->select(c | c.name = 'Science Fiction')"
echo "    ->collect(c | c.books)"
echo "    ->flatten()"
echo "    ->select(b | b.rating >= 4.0)"
echo "    ->collect(b | b.authors)"
echo "    ->flatten()"
echo "    ->asSet()"
echo "    ->sortedBy(a | a.name)"
echo "  Result: Authors of highly-rated sci-fi books, alphabetically"
echo ""
echo "Ex 6: Circular navigation prevention"
echo "  -- Using set operations to avoid duplicates in bidirectional refs"
echo "  library.books->collect(b | b.authors)->flatten()->asSet()"
echo "    ->collect(a | Tuple{"
echo "      author = a.name,"
echo "      uniqueBooks = a.books->asSet()->size()"
echo "    })"
echo "  Result: Authors with unique book counts"
echo ""
echo "✅ Complex navigation enables sophisticated model queries"
echo "✅ Use asSet() to eliminate duplicates in many-to-many relationships"
echo "✅ Flatten after multi-valued navigation before further processing"
