#!/bin/bash
echo "=== AQL Advanced: Let Expressions ===" echo ""
echo "Let expressions bind intermediate results to variables for reuse."
echo ""
echo "Ex 1: Simple let binding"
echo "  let highRated = 4.5 in"
echo "  library.books->select(b | b.rating >= highRated)"
echo "  Result: Books with rating >= 4.5"
echo ""
echo "Ex 2: Multiple let bindings"
echo "  let minRating = 4.0 in"
echo "  let minPages = 300 in"
echo "  library.books->select(b | b.rating >= minRating and b.pages >= minPages)"
echo "  Result: High-quality substantial books"
echo ""
echo "Ex 3: Let with collection binding"
echo "  let availableBooks = library.books->select(b | b.available) in"
echo "  let topRated = availableBooks->select(b | b.rating >= 4.5) in"
echo "  topRated->sortedBy(b | b.rating)->reverse()"
echo "  Result: Available top-rated books, sorted descending"
echo ""
echo "Ex 4: Let with computed value"
echo "  let avgRating = library.books->collect(b | b.rating)->sum() / library.books->size() in"
echo "  library.books->select(b | b.rating > avgRating)"
echo "  Result: Above-average books"
echo ""
echo "Ex 5: Nested let expressions"
echo "  let fiction = library.categories->select(c | c.name = 'Fiction')->first() in"
echo "  let fictionBooks = fiction.books in"
echo "  let avgPages = fictionBooks->collect(b | b.pages)->sum() / fictionBooks->size() in"
echo "  fictionBooks->select(b | b.pages > avgPages)"
echo "  Result: Fiction books longer than category average"
echo ""
echo "✅ Let expressions improve readability and avoid recomputation"
echo "✅ Variables are scoped to the let expression"
echo "✅ Enable building complex queries incrementally"
