#!/bin/bash
echo "=== AQL Advanced: Type Operations ==="
echo ""
echo "Runtime type checking and casting in AQL."
echo ""
echo "Ex 1: oclIsTypeOf - exact type check"
echo "  EObject.allInstances()->select(e | e.oclIsTypeOf(Book))"
echo "  Result: Only Book instances (not subclasses)"
echo ""
echo "Ex 2: oclIsKindOf - type or subtype check"
echo "  -- If there were Book subclasses like EBook, Audiobook:"
echo "  EObject.allInstances()->select(e | e.oclIsKindOf(Book))"
echo "  Result: Books and all subclass instances"
echo ""
echo "Ex 3: oclAsType - safe casting"
echo "  EObject.allInstances()"
echo "    ->select(e | e.oclIsTypeOf(Book))"
echo "    ->collect(e | e.oclAsType(Book))"
echo "    ->collect(b | b.title)"
echo "  Result: Titles of all books"
echo ""
echo "Ex 4: Type filtering with navigation"
echo "  library.eContents()->select(e | e.oclIsKindOf(Book))"
echo "    ->collect(e | e.oclAsType(Book).title)"
echo "  Result: Titles of books directly contained in library"
echo ""
echo "Ex 5: allInstances with type parameter"
echo "  Book.allInstances()"
echo "  Result: All Book instances in the resource set"
echo ""
echo "  Author.allInstances()->collect(a | Tuple{"
echo "    author = a.name,"
echo "    books = a.books->collect(b | b.title)"
echo "  })"
echo "  Result: All authors with their book titles"
echo ""
echo "Ex 6: Type-based conditional logic"
echo "  library.eAllContents()->collect(e | Tuple{"
echo "    type = e.eClass().name,"
echo "    details = if e.oclIsKindOf(Book) then"
echo "                e.oclAsType(Book).title"
echo "              else if e.oclIsKindOf(Author) then"
echo "                e.oclAsType(Author).name"
echo "              else"
echo "                'Unknown'"
echo "              endif endif"
echo "  })"
echo "  Result: All objects with type-specific details"
echo ""
echo "Ex 7: eClass() - get metamodel class"
echo "  library.books->first().eClass().name"
echo "  Result: 'Book'"
echo ""
echo "  library.books->collect(b | b.eClass().eAllAttributes()->collect(a | a.name))"
echo "  Result: Attribute names for Book class (reflective)"
echo ""
echo "✅ Type operations enable generic model processing"
echo "✅ Essential for handling heterogeneous collections"
echo "✅ Support reflective metamodel access"
