#!/bin/bash
echo "=== AQL Advanced: OCL-Style Operations ==="
echo ""
echo "Advanced OCL operations for complex model queries."
echo ""
echo "Ex 1: collectNested - flatten during collect"
echo "  library.categories->collectNested(c | c.books)"
echo "  Equivalent to:"
echo "  library.categories->collect(c | c.books)->flatten()"
echo "  Result: All books from all categories (flattened)"
echo ""
echo "Ex 2: closure - transitive closure"
echo "  -- If Book had 'relatedBooks' reference:"
echo "  book->closure(b | b.relatedBooks)"
echo "  Result: Book and all transitively related books"
echo ""
echo "Ex 3: including / excluding - set operations"
echo "  let baseSet = library.books->select(b | b.rating >= 4.0) in"
echo "  let newBook = library.books->select(b | b.title = 'New Release')->first() in"
echo "  baseSet->including(newBook)"
echo "  Result: High-rated books plus the new release"
echo ""
echo "  library.books->excluding(newBook)"
echo "  Result: All books except the new release"
echo ""
echo "Ex 4: symmetricDifference - XOR of sets"
echo "  let set1 = library.books->select(b | b.rating >= 4.5) in"
echo "  let set2 = library.books->select(b | b.pages >= 400) in"
echo "  set1->symmetricDifference(set2)"
echo "  Result: Books that are EITHER highly rated OR long, but not both"
echo ""
echo "Ex 5: product - Cartesian product"
echo "  let authors = library.authors->first(3) in"
echo "  let books = library.books->first(3) in"
echo "  authors->product(books)->collect(pair | Tuple{"
echo "    author = pair.first.name,"
echo "    book = pair.second.title,"
echo "    actuallyWrote = pair.second.authors->includes(pair.first)"
echo "  })"
echo "  Result: All author-book combinations with authorship flag"
echo ""
echo "Ex 6: iterate - custom accumulation"
echo "  library.books->iterate(b; acc : Integer = 0 |"
echo "    acc + b.pages"
echo "  )"
echo "  Result: Total pages (equivalent to ->collect(b | b.pages)->sum())"
echo ""
echo "Ex 7: any - find arbitrary matching element"
echo "  library.books->any(b | b.rating >= 4.8)"
echo "  Result: Some book with rating >= 4.8 (undefined which one)"
echo ""
echo "Ex 8: one - exactly one match"
echo "  library.books->one(b | b.title = '1984')"
echo "  Result: true if exactly one book titled '1984', false otherwise"
echo ""
echo "✅ OCL operations provide powerful collection manipulation"
echo "✅ closure enables transitive relationship traversal"
echo "✅ iterate allows custom aggregation logic"
