#!/bin/bash
# AQL-02 Step 16: Advanced Filter Patterns

echo "=== AQL Filtering: Advanced Patterns ==="
echo ""
echo "Sophisticated filtering techniques for complex scenarios."
echo ""

echo "Pattern 1: Symmetric Difference (XOR filtering)"
echo "  Find elements in A or B but not both"
echo "  AQL:"
echo "    let highGrade = university.students->select(s | s.grade >= 90) in"
echo "    let youngAge = university.students->select(s | s.age <= 20) in"
echo "    let inHigh = highGrade->select(s | not youngAge->includes(s)) in"
echo "    let inYoung = youngAge->select(s | not highGrade->includes(s)) in"
echo "    inHigh->union(inYoung)"
echo ""
echo "  Result: Students who are EITHER high-performing OR young, but not both"
echo ""

echo "Pattern 2: Top-N filtering"
echo "  AQL:"
echo "    university.students"
echo "      ->sortedBy(s | s.grade)"
echo "      ->reverse()"
echo "      ->first(3)"
echo ""
echo "  Logic: Get top 3 students by grade"
echo "  Result: [Charlie Brown (95), Ivy Chen (94), Jane Smith (92)]"
echo ""

echo "Pattern 3: Percentile filtering"
echo "  AQL:"
echo "    let avgGrade = university.students->collect(s | s.grade)->sum() /"
echo "                   university.students->size() in"
echo "    university.students->select(s | s.grade >= avgGrade)"
echo ""
echo "  Logic: Students above average grade"
echo "  Average: ~82.25"
echo "  Result: Students with 83+ grades"
echo ""

echo "Pattern 4: Conditional filtering based on context"
echo "  AQL:"
echo "    let threshold = if university.students->size() > 100 then 90 else 80 endif in"
echo "    university.students->select(s | s.grade >= threshold)"
echo ""
echo "  Logic: Dynamic threshold based on class size"
echo ""

echo "Pattern 5: Multi-attribute ranking"
echo "  AQL:"
echo "    university.students->select(s |"
echo "      (s.grade >= 90 and s.age >= 21) or"
echo "      (s.grade >= 85 and s.age >= 22)"
echo "    )"
echo ""
echo "  Logic: Different grade thresholds for different age groups"
echo "  Implements age-adjusted performance criteria"
echo ""

echo "Pattern 6: Outlier detection"
echo "  AQL:"
echo "    let avgAge = university.students->collect(s | s.age)->sum() /"
echo "                 university.students->size() in"
echo "    let stdDev = 2.0 in"  # Simplified - would normally calculate
echo "    university.students->select(s |"
echo "      s.age > avgAge + stdDev or s.age < avgAge - stdDev"
echo "    )"
echo ""
echo "  Logic: Find students with unusual ages"
echo ""

echo "Pattern 7: Intersection of multiple filters"
echo "  AQL:"
echo "    let criteria1 = university.students->select(s | s.grade >= 85) in"
echo "    let criteria2 = university.students->select(s | s.age >= 20) in"
echo "    let criteria3 = university.students->select(s | s.studentId.startsWith('S00')) in"
echo "    criteria1->intersection(criteria2)->intersection(criteria3)"
echo ""
echo "  Logic: Students meeting ALL three independent criteria"
echo ""

echo "Pattern 8: Fuzzy matching"
echo "  AQL:"
echo "    let searchTerm = 'john' in"
echo "    university.students->select(s |"
echo "      s.name.toLowerCase().contains(searchTerm.toLowerCase())"
echo "    )"
echo ""
echo "  Logic: Case-insensitive name search"
echo "  Result: [John Doe, Bob Johnson]"
echo ""

echo "Pattern 9: Range-based filtering"
echo "  AQL:"
echo "    university.students->select(s |"
echo "      let gradeRange = Tuple{min=80, max=90} in"
echo "      s.grade >= gradeRange.min and s.grade <= gradeRange.max"
echo "    )"
echo ""
echo "  Logic: Students in specific grade range (80-90)"
echo ""

echo "Pattern 10: Filter with side-effect tracking"
echo "  AQL:"
echo "    let passing = university.students->select(s | s.grade >= 60) in"
echo "    let failing = university.students->select(s | s.grade < 60) in"
echo "    Tuple{"
echo "      passingCount = passing->size(),"
echo "      failingCount = failing->size(),"
echo "      passingStudents = passing"
echo "    }"
echo ""
echo "  Logic: Filter and simultaneously collect statistics"
echo ""

echo "Key principles for advanced filtering:"
echo "  ✓ Use let bindings to avoid recalculation"
echo "  ✓ Combine filters with set operations (union, intersection)"
echo "  ✓ Leverage sorting before filtering for top-N queries"
echo "  ✓ Calculate dynamic thresholds based on data properties"
echo "  ✓ Create reusable filter functions via helpers (in ATL/MTL)"
echo ""

echo "✅ Advanced patterns enable sophisticated data analysis"
