#!/bin/bash
# AQL-02 Step 12: ForAll for Validation

echo "=== AQL Filtering: ForAll for Validation ==="
echo ""
echo "Use forAll to validate data integrity and business rules."
echo ""

echo "Data Integrity Validations:"
echo ""

echo "Validation 1: All students have valid grades"
echo "  AQL: university.students->forAll(s | s.grade >= 0 and s.grade <= 100)"
echo "  Rule: Grades must be 0-100"
echo "  Result: true"
echo "  Purpose: Ensure no data entry errors"
echo ""

echo "Validation 2: All students have IDs"
echo "  AQL: university.students->forAll(s | s.studentId <> null and s.studentId <> '')"
echo "  Rule: Student ID is required"
echo "  Result: true"
echo "  Purpose: Enforce required fields"
echo ""

echo "Validation 3: All courses have positive credits"
echo "  AQL: university.courses->forAll(c | c.credits > 0 and c.credits <= 6)"
echo "  Rule: Credits must be 1-6"
echo "  Result: true"
echo "  Purpose: Valid credit hour range"
echo ""

echo "Business Rule Validations:"
echo ""

echo "Rule 1: All tenured professors must be 40+"
echo "  AQL: university.professors->forAll(p | not p.tenure or p.age >= 40)"
echo "  Logic: If tenured, then age >= 40"
echo "  Equivalent: p.tenure implies p.age >= 40"
echo "  Result: true (all tenured profs are 40+)"
echo ""

echo "Rule 2: No student under 18"
echo "  AQL: university.students->forAll(s | s.age >= 18)"
echo "  Rule: Minimum age requirement"
echo "  Result: true (youngest is Henry Wilson at 18)"
echo ""

echo "Rule 3: All Computer Science courses are advanced (4 credits)"
echo "  AQL: university.courses->forAll(c | c.department <> 'Computer Science' or c.credits = 4)"
echo "  Logic: If CS course, then 4 credits"
echo "  Result: true"
echo ""

echo "Comprehensive Validation Example:"
echo "  AQL:"
echo "    let validStudents = university.students->forAll(s |"
echo "      s.age >= 18 and"
echo "      s.age <= 100 and"
echo "      s.grade >= 0 and"
echo "      s.grade <= 100 and"
echo "      s.studentId <> null"
echo "    ) in"
echo "    let validCourses = university.courses->forAll(c |"
echo "      c.credits > 0 and"
echo "      c.credits <= 6 and"
echo "      c.title <> null"
echo "    ) in"
echo "    let validProfs = university.professors->forAll(p |"
echo "      (not p.tenure or p.age >= 40) and"
echo "      p.specialisation <> null"
echo "    ) in"
echo "    validStudents and validCourses and validProfs"
echo ""

echo "Using validation results:"
echo "  if university.students->forAll(s | s.grade >= 60) then"
echo "    'All students passing'"
echo "  else"
echo "    'At-risk students: ' +"
echo "    university.students->select(s | s.grade < 60)->size().toString()"
echo "  endif"
echo ""

echo "✅ ForAll is essential for data validation"
