#!/bin/bash
# AQL-02 Step 13: Chained Filter Operations

echo "=== AQL Filtering: Chained Filters ==="
echo ""
echo "Chain multiple filter operations for multi-stage filtering."
echo ""

echo "Example 1: Progressive narrowing"
echo "  AQL:"
echo "    university.students"
echo "      ->select(s | s.age >= 20)        # Stage 1: Adults"
echo "      ->select(s | s.grade >= 85)      # Stage 2: High performers"
echo "      ->reject(s | s.grade >= 95)      # Stage 3: Not exceptional"
echo ""
echo "  Stage 1 result: 8 students (20+)"
echo "  Stage 2 result: 5 students (20+ with 85+)"
echo "  Stage 3 result: 4 students (20+, 85-94)"
echo "  Final: [John Doe (85), Jane Smith (92), Alice Williams (88), Frank Miller (90)]"
echo ""

echo "Example 2: Department filtering"
echo "  AQL:"
echo "    university.courses"
echo "      ->reject(c | c.department = 'Humanities')    # Remove Humanities"
echo "      ->reject(c | c.department = 'Chemistry')     # Remove Chemistry"
echo "      ->select(c | c.credits = 4)                  # Keep 4-credit"
echo ""
echo "  Stage 1: Remove English Literature"
echo "  Stage 2: Remove Organic Chemistry"
echo "  Stage 3: Keep only 4-credit courses"
echo "  Result: [Data Structures, Algorithms, Calculus I, Calculus II, Quantum Mechanics]"
echo ""

echo "Example 3: Complex multi-criteria"
echo "  AQL:"
echo "    university.professors"
echo "      ->select(p | p.age < 50)                     # Under 50"
echo "      ->select(p | p.tenure = true)                # Tenured"
echo "      ->reject(p | p.specialisation = 'Chemistry') # Not Chemistry"
echo ""
echo "  Result: [Dr. Alan Turing (45, CS), Dr. Ada Lovelace (42, Math)]"
echo ""

echo "Chaining patterns:"
echo ""

echo "Pattern 1: Successive refinement"
echo "  Start broad, narrow progressively"
echo "  Most restrictive filters first for efficiency"
echo ""

echo "Pattern 2: Category exclusion"
echo "  Remove unwanted categories step-by-step"
echo "  Easier to read than complex OR conditions"
echo ""

echo "Pattern 3: Alternating select/reject"
echo "  Include some criteria, exclude others"
echo "  Natural expression of complex logic"
echo ""

echo "Optimisation tip:"
echo "  Order filters by selectivity (most restrictive first)"
echo "  Reduces intermediate collection sizes"
echo ""

echo "  Less efficient:"
echo "    ->select(common condition)->select(rare condition)"
echo "  More efficient:"
echo "    ->select(rare condition)->select(common condition)"
echo ""

echo "✅ Chaining enables readable multi-stage filtering"
