#!/bin/bash
# AQL-02 Step 8: Chaining Select and Reject

echo "=== AQL Filtering: Chaining Select and Reject ==="
echo ""
echo "Chain multiple filter operations for complex criteria."
echo ""

echo "Example 1: Students with good grades, excluding the very best"
echo "  AQL:"
echo "    university.students"
echo "      ->select(s | s.grade >= 80)"
echo "      ->reject(s | s.grade >= 95)"
echo ""
echo "  Step 1 (select): Get students with 80+"
echo "  Result: [John (85), Jane (92), Alice (88), Charlie (95), Diana (82),"
echo "           Frank (90), Grace (87), Ivy (94)]"
echo ""
echo "  Step 2 (reject): Remove students with 95+"
echo "  Final Result: [John (85), Jane (92), Alice (88), Diana (82),"
echo "                 Frank (90), Grace (87), Ivy (94)]"
echo ""

echo "Example 2: CS courses that aren't 4-credit"
echo "  AQL:"
echo "    university.courses"
echo "      ->select(c | c.department = 'Computer Science')"
echo "      ->reject(c | c.credits = 4)"
echo ""
echo "  Note: In our instance, all CS courses are 4-credit, so result would be empty"
echo ""

echo "Example 3: Three-filter chain"
echo "  AQL:"
echo "    university.students"
echo "      ->select(s | s.age >= 20)"
echo "      ->select(s | s.grade >= 80)"
echo "      ->reject(s | s.age > 22)"
echo ""
echo "  Step 1: Students 20 or older"
echo "  Step 2: Of those, keep only grades 80+"
echo "  Step 3: Of those, remove students over 22"
echo "  Final: Students 20-22 years old with 80+ grades"
echo ""

echo "Order matters in chaining:"
echo "  More restrictive filters first = better performance"
echo "  Smaller intermediate collections = faster processing"
echo ""

echo "Equivalent single select:"
echo "  Chain: ->select(condition1)->select(condition2)"
echo "  Single: ->select(condition1 and condition2)"
echo ""
echo "  Use chaining when:"
echo "    - Conditions are complex and easier to read separately"
echo "    - Intermediate results are useful"
echo "    - Building filters incrementally"
echo ""

echo "✅ Chaining enables multi-stage filtering"
