#!/bin/bash
# AQL-02 Step 15: Filtering with Navigation

echo "=== AQL Filtering: Filter with Navigation ==="
echo ""
echo "Combine filtering with navigation to process filtered results."
echo ""

echo "Example 1: Get names of high-performing students"
echo "  AQL:"
echo "    university.students"
echo "      ->select(s | s.grade >= 90)"
echo "      .name"
echo ""
echo "  Step 1: Filter (select with grade >= 90)"
echo "  Result: [Jane Smith, Charlie Brown, Frank Miller, Ivy Chen]"
echo "  Step 2: Navigate to names"
echo "  Final: ['Jane Smith', 'Charlie Brown', 'Frank Miller', 'Ivy Chen']"
echo ""

echo "Example 2: Get credits of CS courses"
echo "  AQL:"
echo "    university.courses"
echo "      ->select(c | c.department = 'Computer Science')"
echo "      .credits"
echo ""
echo "  Result: [4, 4] (both CS courses are 4 credits)"
echo ""

echo "Example 3: Get ages of tenured professors"
echo "  AQL:"
echo "    university.professors"
echo "      ->select(p | p.tenure = true)"
echo "      .age"
echo ""
echo "  Result: [45, 42, 50, 48] (ages of Dr. Turing, Dr. Lovelace, Dr. Curie, Dr. Hodgkin)"
echo ""

echo "Example 4: Chain navigation after filter"
echo "  AQL: (hypothetical - if Course had Professor reference)"
echo "    university.courses"
echo "      ->select(c | c.credits = 4)"
echo "      .professor.name"
echo ""
echo "  Logic: Get names of professors teaching 4-credit courses"
echo ""

echo "Pattern: Filter-then-Extract"
echo "  collection->select(condition).property"
echo ""
echo "  Benefits:"
echo "    - Extract specific attributes from filtered subset"
echo "    - Smaller result sets"
echo "    - Clear separation of filtering and extraction"
echo ""

echo "Example 5: Multiple properties after filter"
echo "  AQL: (using collect to get multiple properties)"
echo "    university.students"
echo "      ->select(s | s.age >= 21)"
echo "      ->collect(s | Tuple{name=s.name, grade=s.grade})"
echo ""
echo "  Result: Collection of tuples with name and grade for students 21+"
echo ""

echo "Example 6: Navigate then filter"
echo "  AQL:"
echo "    university.students.grade->select(g | g >= 85)"
echo ""
echo "  Step 1: Navigate to all grades"
echo "  Result: [85, 92, 78, 88, 95, 82, 76, 90, 87, 65, 94, 72]"
echo "  Step 2: Filter grades >= 85"
echo "  Final: [85, 92, 88, 95, 90, 87, 94]"
echo ""

echo "Filter-navigate vs. Navigate-filter:"
echo "  Filter-then-navigate: Work with objects, then extract"
echo "    students->select(s | s.grade >= 85).name"
echo ""
echo "  Navigate-then-filter: Extract all, then filter values"
echo "    students.name->select(n | n.size() > 10)"
echo ""

echo "✅ Combining filtering and navigation creates powerful queries"
