#!/bin/bash
# AQL-02 Step 14: Nested Filtering Patterns

echo "=== AQL Filtering: Nested Filtering ==="
echo ""
echo "Use filtering within filter conditions for advanced queries."
echo ""

echo "Example 1: Filter based on collection properties"
echo "  AQL: (hypothetical - if University had Departments)"
echo "    university.departments->select(d |"
echo "      d.courses->select(c | c.credits = 4)->size() > 2"
echo "    )"
echo ""
echo "  Logic: Find departments with more than 2 four-credit courses"
echo "  Nested filter: d.courses->select(c | c.credits = 4)"
echo "  Outer condition: ->size() > 2"
echo ""

echo "Example 2: Cross-collection filtering"
echo "  AQL: (hypothetical - if Students had enrolled Courses)"
echo "    university.students->select(s |"
echo "      s.courses->exists(c | c.department = 'Computer Science')"
echo "    )"
echo ""
echo "  Logic: Find students enrolled in at least one CS course"
echo "  Nested exists: Check within student's course collection"
echo ""

echo "Example 3: Conditional counting"
echo "  AQL: (hypothetical - with Professor-Course relationship)"
echo "    university.professors->select(p |"
echo "      p.courses->select(c | c.credits = 4)->size() >= 2"
echo "    )"
echo ""
echo "  Logic: Professors teaching at least 2 four-credit courses"
echo "  Nested select + size for counting"
echo ""

echo "Pattern: Filter by aggregate properties"
echo "  General form:"
echo "    collection->select(item |"
echo "      item.relatedItems->select(condition)->size() COMPARISON value"
echo "    )"
echo ""
echo "  Variations:"
echo "    - ->exists(...) instead of ->size() > 0"
echo "    - ->forAll(...) for universal properties"
echo "    - ->sum(), ->max(), ->min() for numeric aggregates"
echo ""

echo "Example 4: Multi-level nesting"
echo "  AQL: (hypothetical complex structure)"
echo "    university.departments->select(d |"
echo "      d.professors->exists(p |"
echo "        p.courses->forAll(c | c.students->size() < 30)"
echo "      )"
echo "    )"
echo ""
echo "  Logic: Departments with a professor whose all courses are small"
echo "  Three levels: department → professor → course → students"
echo ""

echo "Best practices for nested filtering:"
echo "  ✓ Keep nesting depth reasonable (max 2-3 levels)"
echo "  ✓ Use meaningful variable names at each level"
echo "  ✓ Break complex queries into let bindings for clarity"
echo "  ✓ Consider performance impact of deep nesting"
echo ""

echo "Alternative with let bindings:"
echo "  let csStudents = university.students->select(s |"
echo "    s.courses->exists(c | c.department = 'Computer Science')"
echo "  ) in"
echo "  let highPerformingCS = csStudents->select(s | s.grade >= 85) in"
echo "  highPerformingCS"
echo ""

echo "✅ Nested filtering enables complex relational queries"
