#!/bin/bash
# Workflow-03: Metamodel Evolution Summary
# Demonstrates safe metamodel evolution from Blog v1 to Blog v2

set -e

# Colour output for better readability
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Colour

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Workflow-03: Metamodel Evolution${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Get the directory where this script is located
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Define file paths
METAMODEL_V1="${SCRIPT_DIR}/workflow-03-step-01-original-metamodel.ecore"
METAMODEL_V2="${SCRIPT_DIR}/workflow-03-step-02-evolved-metamodel.ecore"
MIGRATION_ATL="${SCRIPT_DIR}/workflow-03-step-03-migration-transformation.atl"

echo -e "${YELLOW}Step 1: Validate Original Blog v1 Metamodel${NC}"
echo "Package: http://www.example.org/blog/v1"
echo ""

if command -v swift-ecore &> /dev/null; then
    swift-ecore validate "${METAMODEL_V1}"
    echo -e "${GREEN}✓ Blog v1 metamodel is valid${NC}"
else
    echo -e "${YELLOW}⚠ swift-ecore not found, skipping validation${NC}"
fi
echo ""

echo -e "${YELLOW}Blog v1 Metamodel Structure:${NC}"
echo "  Classes:"
echo "    - Blog (name, description, url)"
echo "      └─ posts [0..*] → Post"
echo "      └─ authors [0..*] → Author"
echo "    - Post (title, content, publishDate)"
echo "      └─ author [1] → Author"
echo "      └─ comments [0..*] → Comment"
echo "    - Author (name, email)"
echo "    - Comment (authorName, content, date)"
echo ""

echo -e "${YELLOW}Step 2: Validate Evolved Blog v2 Metamodel${NC}"
echo "Package: http://www.example.org/blog/v2"
echo ""

if command -v swift-ecore &> /dev/null; then
    swift-ecore validate "${METAMODEL_V2}"
    echo -e "${GREEN}✓ Blog v2 metamodel is valid${NC}"
else
    echo -e "${YELLOW}⚠ swift-ecore not found, skipping validation${NC}"
fi
echo ""

echo -e "${YELLOW}Blog v2 Metamodel Structure (Evolution):${NC}"
echo "  Classes (preserved from v1):"
echo "    - Blog, Post, Author, Comment"
echo ""
echo "  ${GREEN}New Classes (additive changes):${NC}"
echo "    - Category (name, description)"
echo "    - Tag (name)"
echo ""
echo "  ${GREEN}New Attributes in Post:${NC}"
echo "    - slug : String          (URL-friendly identifier)"
echo "    - viewCount : Int = 0    (page view counter)"
echo "    - published : Boolean = false (publication status)"
echo "    - category → Category    (post categorisation)"
echo "    - tags [0..*] → Tag      (post tagging)"
echo ""
echo "  ${GREEN}New Attributes in Author:${NC}"
echo "    - bio : String           (author biography)"
echo "    - avatarUrl : String     (profile picture URL)"
echo ""
echo "  ${GREEN}New References in Blog:${NC}"
echo "    - categories [0..*] → Category"
echo "    - tags [0..*] → Tag"
echo ""

echo -e "${YELLOW}Step 3: Metamodel Evolution Patterns${NC}"
echo ""
echo "  ${GREEN}Additive-Only Evolution Strategy:${NC}"
echo "    ✓ Add new classes (Category, Tag)"
echo "    ✓ Add new attributes with default values"
echo "    ✓ Add new optional references"
echo "    ✓ Preserve all existing classes and attributes"
echo "    ✓ Maintain namespace versioning (v1 → v2)"
echo ""
echo "  ${RED}Avoided Breaking Changes:${NC}"
echo "    ✗ No removal of existing classes"
echo "    ✗ No removal of existing attributes"
echo "    ✗ No changes to cardinality constraints"
echo "    ✗ No changes to required attributes"
echo ""

echo -e "${YELLOW}Step 4: Migration Transformation${NC}"
echo "ATL Transformation: Blog v1 → Blog v2"
echo ""

if [ -f "${MIGRATION_ATL}" ]; then
    echo -e "${GREEN}✓ Migration transformation exists${NC}"
    echo ""
    echo "Transformation Rules:"
    echo "  - Blog2Blog: Migrate blog with new category/tag collections"
    echo "  - Post2Post: Derive slug, set defaults for new attributes"
    echo "  - Author2Author: Add default bio and avatar URL"
    echo "  - Comment2Comment: Preserve unchanged (identity mapping)"
    echo ""
    echo "Helper Functions:"
    echo "  - toSlug(): Generate URL-friendly slug from title"
    echo "  - inferCategory(): Derive category from post content"
    echo "  - extractTags(): Extract tags from post metadata"
    echo ""
    echo "Data Derivation Strategy:"
    echo "  - slug: Convert title to lowercase, replace spaces with hyphens"
    echo "  - viewCount: Initialise to 0"
    echo "  - published: Set to true (existing posts assumed published)"
    echo "  - category: Infer from content keywords"
    echo "  - bio: Default placeholder text"
    echo "  - avatarUrl: Default avatar image URL"
else
    echo -e "${RED}✗ Migration transformation not found${NC}"
fi
echo ""

echo -e "${YELLOW}Step 5: Running the Migration${NC}"
echo ""
echo "To execute the migration transformation:"
echo ""
echo "  # Assuming you have a Blog v1 instance model"
echo "  swift-atl execute \\"
echo "    --transformation ${MIGRATION_ATL} \\"
echo "    --source blog-v1-instance.xmi \\"
echo "    --source-metamodel ${METAMODEL_V1} \\"
echo "    --target blog-v2-instance.xmi \\"
echo "    --target-metamodel ${METAMODEL_V2}"
echo ""

echo -e "${YELLOW}Step 6: Backwards Compatibility${NC}"
echo ""
echo "  ${GREEN}v2 Compatibility with v1:${NC}"
echo "    - All v1 data can be migrated to v2"
echo "    - New attributes have sensible defaults"
echo "    - No data loss during migration"
echo ""
echo "  ${YELLOW}v1 Compatibility with v2:${NC}"
echo "    - v1 tools cannot read v2 models (namespace mismatch)"
echo "    - Requires downgrade transformation if needed"
echo "    - New v2 features would be lost in downgrade"
echo ""

echo -e "${YELLOW}Step 7: Evolution Best Practises${NC}"
echo ""
echo "  1. ${GREEN}Versioning:${NC}"
echo "     - Use explicit version numbers in nsURI (v1, v2, etc.)"
echo "     - Document changes between versions"
echo ""
echo "  2. ${GREEN}Additive Changes:${NC}"
echo "     - Prefer adding new elements over modifying existing ones"
echo "     - Use default values for new required attributes"
echo "     - Make new references optional where possible"
echo ""
echo "  3. ${GREEN}Migration Support:${NC}"
echo "     - Provide ATL transformations for each version increment"
echo "     - Document data derivation strategies"
echo "     - Test migration with realistic data sets"
echo ""
echo "  4. ${GREEN}Deprecation Strategy:${NC}"
echo "     - Mark deprecated elements in documentation"
echo "     - Maintain deprecated elements for at least one version"
echo "     - Provide migration paths before removal"
echo ""

echo -e "${YELLOW}Step 8: Validation Checklist${NC}"
echo ""
echo "  Before deploying evolved metamodel:"
echo "    □ Validate v2 metamodel structure"
echo "    □ Test migration transformation with sample data"
echo "    □ Verify all v1 data migrates successfully"
echo "    □ Check default values are appropriate"
echo "    □ Document breaking changes (if any)"
echo "    □ Update dependent tools and generators"
echo "    □ Test generated code compiles and runs"
echo "    □ Update user documentation"
echo ""

echo -e "${BLUE}========================================${NC}"
echo -e "${GREEN}Metamodel Evolution Complete!${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo "Summary:"
echo "  - Blog v1 → v2 evolution follows additive-only pattern"
echo "  - New features: Categories, Tags, Post metadata, Author profiles"
echo "  - Migration transformation handles data derivation"
echo "  - All existing v1 data preserved and enhanced"
echo ""
echo "Next Steps:"
echo "  - Create sample Blog v1 instance model"
echo "  - Run migration transformation"
echo "  - Validate migrated v2 instance"
echo "  - Generate Swift code from v2 metamodel"
echo "  - Build applications using evolved model"
echo ""
