#!/bin/bash
echo "=== Running ATL Transformation: Shop to Reporting ==="
echo ""
echo "Input Model: workflow-01-step-05-instance.xmi (TechStore)"
echo "Transformation: workflow-01-step-10-transformation.atl"
echo "Output: sales-report.xmi"
echo ""
echo "Executing transformation..."
echo "swift-atl transform \\"
echo "  --source-metamodel workflow-01-step-01-metamodel.ecore \\"
echo "  --target-metamodel workflow-01-step-09-reporting-metamodel.ecore \\"
echo "  --source-model workflow-01-step-05-instance.xmi \\"
echo "  --transformation workflow-01-step-10-transformation.atl \\"
echo "  --output sales-report.xmi"
echo ""
echo "Expected Output Structure:"
echo "  SalesReport {"
echo "    reportId: 'REPORT-2024-01-15T10:30:00Z'"
echo "    totalRevenue: 15847.00  (sum of all order totals)"
echo "    totalOrders: 10"
echo "    categoryMetrics: ["
echo "      { categoryName: 'Electronics', productCount: 3, totalSales: 8897.00 }"
echo "      { categoryName: 'Computers', productCount: 4, totalSales: 5450.00 }"
echo "      { categoryName: 'Accessories', productCount: 3, totalSales: 1500.00 }"
echo "    ]"
echo "    customerMetrics: ["
echo "      { customerId: 'C001', name: 'Alice Johnson', orderCount: 2, totalSpent: 2798.00 }"
echo "      { customerId: 'C002', name: 'Bob Smith', orderCount: 1, totalSpent: 1299.00 }"
echo "      ..."
echo "    ]"
echo "    productMetrics: ["
echo "      { productId: 'P001', name: 'Laptop Pro', unitsSold: 5, revenue: 4995.00 }"
echo "      { productId: 'P002', name: 'Wireless Mouse', unitsSold: 12, revenue: 348.00 }"
echo "      ..."
echo "    ]"
echo "  }"
echo ""
echo "✅ Transformation demonstrates Shop → Reporting metamodel mapping"
echo "✅ Aggregates sales data across customers, categories, and products"
echo "✅ Calculates metrics: revenue, order counts, averages"
