#!/bin/bash
echo "=== MTL Code Generation from Sales Report ==="
echo ""
echo "Step 1: Generate Swift API"
echo "  swift-mtl generate \\"
echo "    --metamodel workflow-01-step-09-reporting-metamodel.ecore \\"
echo "    --model sales-report.xmi \\"
echo "    --template workflow-01-step-13-swift-templates.mtl \\"
echo "    --output-dir ./generated/swift"
echo ""
echo "  Generated file: generated/swift/SalesReportAPI.swift"
echo "  - SalesReportAPI struct with all metrics"
echo "  - CategoryMetricAPI, CustomerMetricAPI, ProductMetricAPI"
echo "  - Computed properties: averageOrderValue, topCategory, topCustomer, topProduct"
echo "  - Summary generation methods"
echo ""
echo "Step 2: Generate JSON Schema"
echo "  swift-mtl generate \\"
echo "    --metamodel workflow-01-step-09-reporting-metamodel.ecore \\"
echo "    --model sales-report.xmi \\"
echo "    --template workflow-01-step-14-json-templates.mtl \\"
echo "    --output-dir ./generated/json"
echo ""
echo "  Generated files:"
echo "    - generated/json/sales-report-schema.json (JSON Schema v7)"
echo "    - generated/json/sales-report-instance.json (JSON data)"
echo ""
echo "Step 3: Generate Documentation"
echo "  swift-mtl generate \\"
echo "    --metamodel workflow-01-step-09-reporting-metamodel.ecore \\"
echo "    --model sales-report.xmi \\"
echo "    --template workflow-01-step-15-docs-templates.mtl \\"
echo "    --output-dir ./generated/docs"
echo ""
echo "  Generated file: generated/docs/SalesReportDocumentation.md"
echo "  - Executive summary with key metrics"
echo "  - Category performance breakdown"
echo "  - Customer analytics and segmentation"
echo "  - Product performance tables"
echo "  - Insights and recommendations"
echo ""
echo "Output Directory Structure:"
echo "  generated/"
echo "  ├── swift/"
echo "  │   └── SalesReportAPI.swift"
echo "  ├── json/"
echo "  │   ├── sales-report-schema.json"
echo "  │   └── sales-report-instance.json"
echo "  └── docs/"
echo "      └── SalesReportDocumentation.md"
echo ""
echo "✅ MTL templates transform models into multiple output formats"
echo "✅ Single source model → multiple target artefacts"
echo "✅ Demonstrates Model-to-Text transformation power"
