//
// GenerateCommand.swift
// ECore
//
//  Created by Rene Hexel on 3/12/2025.
//  Copyright © 2025 Rene Hexel. All rights reserved.
//
import ArgumentParser
import Foundation
import ModellingCommandLine
import ModellingGenerators

/// Command for generating code from models.
///
/// The generate command creates source code in various target languages from Ecore metamodels
/// or generator models. Every language has a template set, such as C, C++, Java and Swift, and is
/// generated from a generator model (`.genmodel`) by the template engine; an Ecore model is
/// imported into a temporary generator model first.
struct GenerateCommand: AsyncParsableCommand {
    static let configuration = CommandConfiguration(
        commandName: "generate",
        abstract: "Generate code from models",
        discussion: """
            Every language is generated by a template set from a generator model (.genmodel, see \
            the genmodel command) or an Ecore model, which is imported into a temporary generator \
            model first.

            Languages with a template set: \(templateLanguageList())

            Template files in the directories given with --template-path replace the bundled \
            templates of the same name, and a directory there that holds a template set adds a \
            language. Existing files are merged with the generated code unless --force-overwrite \
            or --diff says otherwise.

            An Ecore model given for a template language is imported with the generator model \
            defaults of the headless Eclipse generator. --defaults wizard gives the settings of \
            the interactive Eclipse wizard instead, and --root-extends-class, --operation-reflection \
            and --import-organizing (or their --no- forms) override single settings.

            Code styles of the template sets (--code-style): \(CodeStyleOptions.bundledStyleList())
            """
    )

    /// The names of the template set languages that are bundled, as text for the help.
    ///
    /// - Returns: The language names, separated by commas.
    static func templateLanguageList() -> String {
        TemplateSet.availableLanguages().joined(separator: ", ")
    }

    /// Input model file path.
    @Argument(help: "Input model file path (.genmodel or .ecore)")
    var inputPath: String

    /// Output directory for generated code.
    @Option(name: .shortAndLong, help: "Output directory for generated code")
    var output: String = "."

    /// Target language for code generation.
    @Option(
        name: .shortAndLong,
        help: "Target language: the name of a template set such as swift, java, c or cpp (see the discussion)")
    var language: String = "swift"

    /// The preset and the overrides of the generator model defaults.
    @OptionGroup(title: "Generator model defaults")
    var genModelDefaults: GenModelDefaultsOptions

    /// The code style of the generated text.
    @OptionGroup(title: "Code style")
    var codeStyle: CodeStyleOptions

    /// Directories whose template files replace the bundled templates.
    @Option(
        name: .customLong("template-path"),
        help: "A directory with template files that replace bundled templates (can be repeated)")
    var templatePaths: [String] = []

    /// Whether existing files are replaced.
    @Flag(name: .customLong("force-overwrite"), help: "Replace existing files without merging")
    var forceOverwrite: Bool = false

    /// Whether the differences with existing files are written beside them.
    @Flag(help: "Write the generated text of existing files beside them as .<name>.new")
    var diff: Bool = false

    /// Whether the model directory of the generator model is part of the output location.
    @Flag(
        name: .customLong("model-directory"),
        help: "Write below the model directory of the generator model, such as <output>/project/src")
    var useModelDirectory: Bool = false

    /// Enable verbose output.
    @Flag(name: .shortAndLong, help: "Enable verbose output")
    var verbose: Bool = false

    /// Executes the generate command.
    ///
    /// Generates code in the specified target language from the input model.
    ///
    /// - Throws: `GenerationError` if generation fails.
    @MainActor
    func run() async throws {
        guard FileManager.default.fileExists(atPath: inputPath) else {
            throw GenerationError.fileNotFound(inputPath)
        }
        let inputURL = URL(fileURLWithPath: inputPath)
        let templateURLs = templatePaths.map { URL(fileURLWithPath: $0) }
        let templateLanguages = TemplateSet.availableLanguages(templatePaths: templateURLs)
        guard templateLanguages.contains(language) else {
            throw GenerationError.unknownLanguage(language, templateLanguages)
        }
        if genModelDefaults.isGiven && inputURL.pathExtension.lowercased() != "ecore" {
            throw ArgumentParser.ValidationError(
                "The generator model defaults only apply to an Ecore model generated with a template language")
        }
        try await generateFromTemplates(input: inputURL, templateURLs: templateURLs)
    }

    // MARK: - Template sets

    /// Generates code from a generator model or an Ecore model with a template set.
    private func generateFromTemplates(input: URL, templateURLs: [URL]) async throws {
        var options = GenerationOptions(
            templatePaths: templateURLs, forceOverwrite: forceOverwrite, diff: diff)
        if useModelDirectory { options.includeSourceRoot = true }
        codeStyle.apply(to: &options)
        var importOptions = GenModelImportOptions()
        genModelDefaults.apply(to: &importOptions)
        let bar = GenerationProgressBar(verbose: verbose)
        if verbose {
            print("Generating \(language) code from: \(input.path)")
            print("Output directory: \(output)")
        }
        let result: ModellingGenerators.GenerationResult
        do {
            result = try await ModellingGenerators.GenerationPipeline.generate(
                inputURL: input, language: language, outputDirectory: URL(fileURLWithPath: output),
                importOptions: importOptions, options: options, progress: bar.reporter)
        } catch {
            bar.finish()
            throw error
        }
        bar.finish()
        let noun = result.files.count == 1 ? "file" : "files"
        print("Generated \(result.files.count) \(noun) in: \(result.outputDirectory.path)")
    }
}
